EliteFifa\CompetitionBundle\Entity\Competition:
  type: entity
  repositoryClass: EliteFifa\CompetitionBundle\Repository\CompetitionRepository
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discr
    type: string
  discriminatorMap:
    league: EliteFifa\CompetitionBundle\Entity\League
    knockout: EliteFifa\CompetitionBundle\Entity\Knockout
    multistage: EliteFifa\CompetitionBundle\Entity\MultiStage
  table: competition
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    code:
      type: string
      length: 100
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          fields:
            - name
  manyToMany:
    competitors:
      targetEntity: EliteFifa\CompetitorBundle\Entity\Competitor
      mappedBy: competitors
    seasons:
      targetEntity: EliteFifa\SeasonBundle\Entity\Season
      inversedBy: competitions
      cascade: ["persist"]
  manyToOne:
    association:
      targetEntity: EliteFifa\AssociationBundle\Entity\Association
      inversedBy: competitions
      cascade: ["persist"]
      joinColumn:
        name: association_id
        referencedColumnName: id
    region:
      targetEntity: EliteFifa\RegionBundle\Entity\Region
      inversedBy: competitions
      cascade: ["persist"]
      joinColumn:
        name: region_id
        referencedColumnName: id
  oneToMany:
    matches:
      targetEntity: EliteFifa\MatchBundle\Entity\Match
      mappedBy: competition
      cascade: ["persist"]
  oneToOne:
    stage:
      targetEntity: EliteFifa\CompetitionBundle\Entity\Stage
      joinColumn:
        name: stage_id
        referencedColumnName: id
        onDelete: set null