EliteFifa\CompetitionBundle\Entity\Stage:
  type: entity
  repositoryClass: EliteFifa\CompetitionBundle\Repository\StageRepository
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discr
    type: string
  discriminatorMap:
    group: EliteFifa\CompetitionBundle\Entity\GroupStage
    knockout: EliteFifa\CompetitionBundle\Entity\KnockoutStage
  table: stage
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    parent:
      targetEntity: EliteFifa\CompetitionBundle\Entity\MultiStage
      inversedBy: stages
      cascade: ["persist"]
      joinColumn:
        name: parent_id
        referencedColumnName: id
  oneToOne:
      nextStage:
        targetEntity: EliteFifa\CompetitionBundle\Entity\Stage
        cascade: ["persist"]
        joinColumn:
          name: next_stage_id
          referencedColumnName: id
          onDelete: set null