elite_fifa.simulate_matches:
    path: /admin/match/simulate/{competitorId}
    defaults: { _controller: MatchBundle:AdminMatch:simulate }

elite_fifa.show_match:
    path: /match/{id}
    defaults: { _controller: MatchBundle:Match:show }

elite_fifa.list_matches:
    path: /matches
    defaults: { _controller: MatchBundle:Match:list }

elite_fifa.report_ladder_match:
    path: /match/report/ladder
    defaults: { _controller: MatchBundle:Match:reportLadder }

elite_fifa.report_match:
    path: /match/report/{id}
    defaults: { _controller: MatchBundle:Match:report }

elite_fifa.confirm_match:
    path: /match/confirm/{id}
    defaults: { _controller: MatchBundle:Match:confirm }
