EliteFifa\UserBundle\Entity\Role:
  type: entity
  repositoryClass: EliteFifa\UserBundle\Repository\RoleRepository
  table: role
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 30
    role:
      type: string
      length: 20
      unique: true
  manyToMany:
    users:
      targetEntity: EliteFifa\UserBundle\Entity\User
      mappedBy: roles