parameters:
    # repositories
    career_repository.class:        EliteFifa\CareerBundle\Repository\CareerRepository
    career_repository.factory_argument: 'CareerBundle:Career'

    # services
    career_service.class:           EliteFifa\CareerBundle\Service\CareerService

    # listeners
    update_career_listener.class: EliteFifa\CareerBundle\EventListener\UpdateCareerListener

services:
    # services
    elite_fifa.career_service:
        class: %career_service.class%
        arguments:
          - '@elite_fifa.career_repository'

    # repositories
    elite_fifa.career_repository:
        class: %career_repository.class%
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - %career_repository.factory_argument%

    # listeners
    elite_fifa.update_career_listener:
        class: %update_career_listener.class%
        arguments:
            - '@elite_fifa.career_service'
        tags:
            - { name: kernel.event_listener, event: job-application.accepted, method: onJobApplicationAccepted }